### PR TITLE
Development

### PR DESCRIPTION
**Pull request by blbi0875**
Images and logos for website
logonew
name
namelandscape

### CODE REVIEW

**Comment by kewh9902** [comment]
The logos look amazing good job!!!

**Comment by blbi0875** [comment]
Thanks so much for saying that man. It really means a lot.

**Comment by blbi0875** [comment]
Thanks so much for saying that about the logos man. That was very nice of
you. It really means a lot.

**Review by keatonjwhitehead — APPROVED** [review]

**Comment by SuyogSoti** [comment]
I will fix this after treasure merges into development

**Pull request merged**
